apiVersion: apps/v1
kind: Deployment
metadata:
  name: noticia-api
  labels:
    app: api-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - name: api-noticia-container
          image: jo4ovictor/api-noticia:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-noticia-service
spec:
  selector:
    app: crud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
