name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obter Código Fonte
        uses: actions/checkout@v3.6.0

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
            
      - name: Docker Build
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./NoticiarioAPI
          file: ./NoticiarioAPI/Dockerfile
          push: true
          tags: |
            jo4ovictor/api-noticia:v${{ github.run_number }}
            jo4ovictor/api-noticia:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Obter Código Fonte
        uses: actions/checkout@v3.6.0
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: rg-noticia
          cluster-name: techNoticia
          
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/pvc.yml
            k8s/sql-server-deploy.yml
            k8s/api-deploy.yml
          images: |
            jo4ovictor/api-noticia:v${{ github.run_number }}

            
